version: '3.8'

services:
  db:
    image: mariadb
    container_name: selling_my_car_db
    restart: always
    env_file:
      - .env
    command:
      - --default-authentication-plugin=mysql_native_password
      - --max-allowed-packet=268435456
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --skip-character-set-client-handshake
    volumes:
      - ${PWD}/database:/var/lib/mysql
    ports:
      - '${DB_PORT}:3306'
  api:
    image: ${DOCKER_REGISTRY_B}:main
    container_name: selling_my_car_api
    restart: always
    env_file:
      - .env
    ports:
      - ${API_PORT}:8080
    volumes: 
      - ${PWD}/api:/home
    depends_on:
      - db
  # web:
  #   image: ${DOCKER_REGISTRY_F}:main
  #   restart: always
  #   env_file:
  #     - '.env'
  #   ports:
  #     - ${API_PORT}:3000
  #   depends_on:
  #     - api