version: '3.8'

# volumes:
#   selling_my_car:

services:
  # web:
  #   image: ${DOCKER_REGISTRY_F}:main
  #   restart: always
  #   env_file:
  #     - '.env'
  #   ports:
  #     - ${API_PORT}:3000
  #   depends_on:
  #     - api
  api:
    image: ${DOCKER_REGISTRY_B}:main
    restart: always
    env_file:
      - .env
    ports:
      - ${API_PORT}:8000
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    env_file:
      - .env
    command:
      - --default-authentication-plugin=mysql_native_password
      - --max-allowed-packet=268435456
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --skip-character-set-client-handshake
    volumes:
      - /Users/ddino/project/test:/var/lib/mysql/
    ports:
      - '${DB_PORT}:3306'