version: '3.8'

services:
  selling_my_car_db:
    image: mariadb
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --max-allowed-packet=268435456
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --skip-character-set-client-handshake
    volumes:
      - ${PWD}/database:/var/lib/mysql
    environment:
      - TZ=Asia/Seoul
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthchueck:
      test: ["CMD", "echo 'SELECT version();'| mysql"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - ${DB_PORT}:${MYSQL_PORT}

  selling_my_car_api:
    image: ${DOCKER_REGISTRY_B}:main
    restart: always
    ports:
      - ${API_PORT}:8088
    volumes: 
      - ${PWD}/api:/home
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      - AWS_IMAGE_URL=${AWS_IMAGE_URL}
    depends_on:
      - selling_my_car_db

  selling_my_car_web:
    image: ${DOCKER_REGISTRY_F}:dev
    restart: always
    ports:
      - ${WEB_PORT}:3000
    depends_on:
      - selling_my_car_api